language: csharp
mono: none
dotnet: 3.1.200

install:
  - dotnet restore ./src/PayX.sln

script:
  - dotnet build ./src/PayX.sln -c Release
  - dotnet test ./src/PayX.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script: 
  - bash <(curl -s https://codecov.io/bash)