sudo: required

language: csharp
mono: none
dotnet: 3.1.200
services:
  - docker

install:
  - dotnet restore ./src/PayX.sln

script:
  - dotnet build ./src/PayX.sln -c Release
  - dotnet test ./src/PayX.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_success:
  - docker build -t andrevitorlopes/payx .
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push andrevitorlopes/payx

after_script: 
  # Push codecoverage results to Codecov
  - bash <(curl -s https://codecov.io/bash)